---
- pip: name=awscli

- name: "Assures {{ awscli_credentials_path }} dir exists"
  file:
    path: "{{ awscli_credentials_path }}"
    state: directory

- name: Configure AWS backup credential
  template:
    src: files/aws-credential.j2
    dest: "{{ awscli_credentials_path }}/credentials"
    owner: root
    group: root
    mode: 0600
  when: access_key is defined

- name: Configure AWS backup config
  template:
    src: files/aws-config.j2
    dest: "{{ awscli_credentials_path }}/config"
    owner: root
    group: root
    mode: 0600
  when: access_key is defined

