---
- pip: name=awscli

- name: Assures .aws dir exists
  file:
    path: "{{ item.path }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: 0755
    state: directory
  with_items: "{{ awscli_credentials }}"

- name: Configure AWS backup credential
  template:
    src: files/aws-credential.j2
    dest: "{{ item.path }}/credentials"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: 0600
  with_items: "{{ awscli_credentials }}"
  when: access_key is defined

- name: Configure AWS backup config
  template:
    src: files/aws-config.j2
    dest: "{{ item.path }}/config"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: 0600
  with_items: "{{ awscli_credentials }}"
  when: access_key is defined
