---
- name: Installing cronlock
  copy: >
    src=cronlock
    dest=/usr/bin/cronlock
    owner=root
    group=root
    mode=0755


- name: Configure cronlock
  template: >
    src=cronlock.conf.j2
    dest=/etc/cronlock.conf
    mode=0644
  when: cronlock_host is defined and ec2_tag_project is defined

- name: jobs
  cron: >
    name="{{item.name}}"
    job="{{ item.job}}"
    minute={{ item.minute|default('*') }}
    hour={{ item.hour|default('*') }}
    day={{ item.day|default('*') }}
    month={{ item.month|default('*') }}
    weekday={{ item.weekday|default('*') }}
    cron_file={{ item.file|default(cron_file) }}
    user={{ item.user|default('root') }}
    state={{ item.state|default('present') }}
  with_items: crons
  notify:
    - cron restart
  when: crons|length > 0
  sudo: yes
