---
- name: Create base directory
  file: path=/opt/cycloid/bin
        state=directory

- name: Install list of packages
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
    - git-core
    - vim
    - tmux
    - htop
    - unzip
    - telnet
    - ntp
    - python-pip
    - locales
    - apt-transport-https
    - lsof

- locale_gen: name=fr_FR.UTF-8 state=present

- name: "Vim config file"
  copy: src=vimrc
        dest=/etc/vim/vimrc

- group: name=admin state=present
- user: name=admin group=admin shell=/bin/bash state=present

