
- name: "Setup hostname"
  hostname: name={{ec2_tag_Name}} 
  when: ec2_tag_Name is defined

- name: "Setup AWS host"
  lineinfile: dest=/etc/hosts line="{{item}} {{hostvars[item]['ec2_tag_Name']}}" owner=root group=root mode=0644
  with_items: play_hosts
  when: ec2_tag_Name is defined


#debug: msg="host={{item}}, hostname={{hostvars[item]['ec2_tag_Name']}}"

