---
- name: Setup global hosts
  lineinfile: dest=/etc/hosts
              line="{{item}}"
              state=present
              owner=root 
              group=root 
              mode=0644
  with_items: global_hosts
  when: global_hosts is defined

- name: "Setup hostname"
  hostname: name={{ec2_tag_Name}}
  when: ec2_tag_Name is defined

- name: "Set facts with hostname"
  set_fact: ansible_hostname={{ec2_tag_Name}}
  when: ec2_tag_Name is defined

- name: "Setup AWS Hosts"
  lineinfile: dest=/etc/hosts
              regexp='^{{ item }}.*'
              line="{{ item }}
                {{hostvars[item].ec2_tag_Name}}
                {{custom_hosts[hostvars[item].ec2_tag_Name]|default([])|join(' ')}}"
              state=present
  with_items: play_hosts
  when: ec2_tag_Name is defined

- name: "Register instance private DNS"
  route53:
    command: "create"
    zone: "{{ r53_internal_zone }}"
    record: "{{ ec2_tag_Name }}"
    type: "A"
    ttl: "7200"
    value: "{{ ansible_eth0.ipv4.address }}"
  when: r53_internal_zone is defined

# debug: msg="host={{item}}, hostname={{hostvars[item]['ec2_tag_Name']}}
