---
- name: Setup global hosts
  lineinfile: dest=/etc/hosts
              line="{{item}}"
              state=present
              owner=root 
              group=root 
              mode=0644
  with_items: global_hosts
  when: global_hosts is defined

- name: Setup link hosts
  lineinfile: dest=/etc/hosts
              line="{{ hostvars[item.link].ansible_default_ipv4.address }} {{item.target}}"
              state=present
              owner=root 
              group=root 
              mode=0644
  with_items: aws_link_hosts
  when: aws_link_hosts is defined and ec2_tag_Name is defined
 
- name: "Setup hostname"
  hostname: name={{ec2_tag_Name}} 
  when: ec2_tag_Name is defined

- name: "Setup AWS host"
  lineinfile: dest=/etc/hosts
              line="{{item}} {{hostvars[item]['ec2_tag_Name']}}"
              owner=root 
              group=root 
              mode=0644
  with_items: play_hosts
  when: ec2_tag_Name is defined


# debug: msg="host={{item}}, hostname={{hostvars[item]['ec2_tag_Name']}}
