---
# tasks file for base

- include: deps.yml
  tags: deps
  when: deps

- include: ssh.yml
  tags: ssh
  when: ssh

- include: aws-cli.yml
  tags: aws-cli
  when: aws-cli

- include: hosts.yml
  tags: hosts
  when: hosts

- include: cron.yml
  tags: cron

- include: backup.yml
  tags: backup
  when: backup
