---
# tasks file for base

- include: jessie-fix.yml
  tags: jessie-fix
  when: ansible_os_family == "Debian" and ansible_distribution_release == "jessie"

- include: deps.yml
  tags: deps
  when: deps

- include: ssh.yml
  tags: ssh
  when: ssh

- include: bashrc.yml
  tags: bashrc

- include: aws-cli.yml
  tags: aws-cli
  when: awscli

- include: hosts.yml
  tags: hosts
  when: hosts

- include: cronlock.yml
  tags: cron

- include: backup.yml
  tags: backup
  when: backup
